# Generated by Django 6.1 on 2026-08-31 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EffectivenessIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension', models.CharField(choices=[('EFFICIENCY', 'Efficiency'), ('ACCURACY', 'Accuracy'), ('ACCESSIBILITY', 'Accessibility'), ('USABILITY', 'Usability / Satisfaction'), ('HR_EFFECTIVENESS', 'HR Effectiveness'), ('ATTENDANCE', 'Attendance'), ('PERFORMANCE_MGMT', 'Performance Management'), ('REPORTING', 'Reporting')], max_length=25)),
                ('indicator_name', models.CharField(max_length=150)),
                ('period', models.CharField(choices=[('BASELINE', 'Baseline (Pre-Implementation)'), ('POST_IMPLEMENTATION', 'Post-Implementation')], max_length=25)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(help_text="e.g. 'days', '%', 'count'", max_length=30)),
                ('measured_on', models.DateField()),
                ('source_note', models.CharField(help_text="Where this number came from (e.g. 'HR manual log, n=42' or 'system-calculated from Attendance model'). Required for academic honesty — never leave blank with a fabricated figure.", max_length=255)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'effectiveness_indicator',
                'ordering': ['dimension', 'indicator_name', 'period'],
            },
        ),
        migrations.CreateModel(
            name='SatisfactionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answers', models.JSONField(help_text='e.g. {"ease_of_use": 4, "usefulness": 5, "reliability": 4, "overall_satisfaction": 5}')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'satisfaction_response',
            },
        ),
    ]
