# Generated by Django 6.1 on 2026-08-31 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_open', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'performance_cycle',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Relative weight used in the weighted final score. Weights across a cycle should sum sensibly (validated at cycle level, not enforced to exactly 100 here).', max_digits=5)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='performance.performancecycle')),
            ],
            options={
                'db_table': 'performance_criterion',
                'unique_together': {('cycle', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('OPEN', 'Open'), ('SELF_ASSESSED', 'Self-Assessment Submitted'), ('SUPERVISOR_ASSESSED', 'Supervisor Assessment Submitted'), ('FINALIZED', 'Finalized'), ('ACKNOWLEDGED', 'Acknowledged by Employee')], default='OPEN', max_length=25)),
                ('self_assessment_comment', models.TextField(blank=True)),
                ('supervisor_comment', models.TextField(blank=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('employee_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='performance.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_evaluations', to='employees.employee')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'performance_evaluation',
            },
        ),
        migrations.CreateModel(
            name='PerformanceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField(help_text='Raw score on the configured scale (e.g. 1-5).')),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='performance.performancecriterion')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='performance.performanceevaluation')),
            ],
            options={
                'db_table': 'performance_score',
            },
        ),
        migrations.AddIndex(
            model_name='performanceevaluation',
            index=models.Index(fields=['stage'], name='performance_stage_79e83d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performanceevaluation',
            unique_together={('cycle', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='performancescore',
            unique_together={('evaluation', 'criterion')},
        ),
    ]
