# Generated by Django 6.1 on 2026-08-31 03:03

import apps.documents.models
import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('EMPLOYMENT', 'Employment Document'), ('IDENTIFICATION', 'Identification Document'), ('CERTIFICATE', 'Certificate'), ('CONTRACT', 'Contract'), ('PERFORMANCE', 'Performance Document'), ('OTHER', 'Other HR Document')], default='OTHER', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/claude/miu_ems/private_media'), upload_to=apps.documents.models.document_upload_path, validators=[apps.documents.models.validate_document_file])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_document',
                'ordering': ['-created_at'],
            },
        ),
    ]
