# Generated by Django 6.1 on 2026-08-31 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('ON_LEAVE', 'On Leave'), ('EXCUSED', 'Excused'), ('REMOTE', 'Remote/Other')], default='PRESENT', max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'attendance_record',
                'ordering': ['-date'],
            },
        ),
    ]
