# Generated by Django 6.1 on 2026-08-31 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('EMPLOYEE_CREATED', 'Employee Created'), ('EMPLOYEE_UPDATED', 'Employee Updated'), ('EMPLOYEE_DEACTIVATED', 'Employee Deactivated'), ('LEAVE_SUBMITTED', 'Leave Submitted'), ('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected'), ('ATTENDANCE_CREATED', 'Attendance Created'), ('ATTENDANCE_UPDATED', 'Attendance Updated'), ('PERFORMANCE_CREATED', 'Performance Record Created'), ('PERFORMANCE_FINALIZED', 'Performance Finalized'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_DOWNLOADED', 'Document Downloaded'), ('REPORT_GENERATED', 'Report Generated'), ('ROLE_CHANGED', 'Role Changed'), ('PERMISSION_DENIED', 'Permission Denied')], max_length=40)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='audit_log_action_09d227_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_log_object__8ccc11_idx')],
            },
        ),
    ]
